
DISTANCE = 'distance'
DEGREE = 'degree'
BETWEENNESS = 'betweenness'
CLOSENESS = 'closeness'
PAGE_RANK = 'pagerank'
SIZE = 'size'
COMPLETE_RATIO = 'complete_ratio'
CLUSTER_COEFF = 'cluster_coefficient'
FEATURE_VECTOR = 'h'
UNA_RATIO = 'una_ratio'
BRIDGES = 'bridges'